### ISSUE TITLE
Resending invitaions via pending invites

### ISSUE THREAD

**Issue by Semir1212** [humhub/massuserimport-issues#20]
HH 1.16.2
Mass User Import 1.2.6

If the source of the invitation was the Mass User Import module and the invitation is resent via Administration --> Users --> ‘List Pending Registrations’, the invitation does not appear to be sent. The resend with other sources works as expected.

**Comment by yurabakhtin** [comment]
@luke- The problem exists because on run the sending from core side we find the `Invite` record as `Invite::findOne(['id' => $id])`, but this module has a specific class `ExtendedUserInvite extends Invite`, and the class has own code for the method `sendInviteMail()`, so we should somehow find a solution to fallback the record `Invite` to `ExtendedUserInvite` when `source = 'massinvite'`.
I have tried the event `Invite::EVENT_AFTER_FIND` but it doesn't help to override the core `Invite` object with the module `ExtendedUserInvite`. I will try to test other ways tomorrow or we will need to add new event to handle it.

**Comment by luke-** [comment]
@yurabakhtin Thank you!

**Comment by yurabakhtin** [comment]
@luke- I didn't find how to override the core class `Invite` with the module class `ExtendedUserInvite`.
I have tried to use event `EVENT_AFTER_FIND` and also by `Yii::$classMap` and `Yii::$container->set()` but it doesn't work, so I have created the new event `Invite::EVENT_AFTER_SEND` in the core master PR https://github.com/humhub/humhub/pull/7229.
Module PR https://github.com/humhub/massuserimport/pull/30 - please note I have increased min version to 1.16, but probably it should be `1.16.3`.

**Comment by luke-** [comment]
@yurabakhtin Do I understand the problem correctly: you are trying to modify the “Resend Invite” button in Core so that it uses the MassUserInvite Resend?

---

What do you think about following, simplier approach: 

- If the source is 'massuserimport' or something else than what is used in core, we do not display the button "Resend". (in core).
- Users must then always do the resend exclusively via the MassUserImport module.

**Comment by yurabakhtin** [comment]
@luke- As I understand you want to hide the button from here if it is not core source:

![mass-buttons](https://github.com/user-attachments/assets/52aabb8e-f337-4f6c-bfaa-cf0755f0efa2)

so the actions will be processed only here by the external module:

![mass-module-page](https://github.com/user-attachments/assets/9f9fac15-a26d-45ab-bb2f-4b580e32c919)

I am not sure how it is ok, it would be good to know from people how use the module.

I am thinking about why the value like `massinvite` is stored there instead of the class name like `humhub\modules\massuserimport\models\ExtendedUserInvite`, so we could know what object to call to send, however it seems not easy to implement and we need to touch a core code either.

**Comment by luke-** [comment]
@yurabakhtin 

> @luke- As I understand you want to hide the button from here if it is not core source:
> 
Yes, exactly. From my side, we could also hide the complete entry from the ore “Pending Registration” page, when the row has an unknown source. (from core perspective).
> 
> so the actions will be processed only here by the external module:
> 

Not displaying the entries at all would make the separation between core and module even clearer.

> 
> I am not sure how it is ok, it would be good to know from people how use the module.
> 
> I am thinking about why the value like `massinvite` is stored there instead of the class name like `humhub\modules\massuserimport\models\ExtendedUserInvite`, so we could know what object to call to send, however it seems not easy to implement and we need to touch a core code either.

Yes, your approach would definitely be more user-friendly. I feel it's a bit too complicated to also support a “polymorphic” relation there. 

I'll discuss with @Semir1212  & Co. which way we should go.

**Comment by luke-** [comment]
Just discussed: Let's go with completely hide unknown invite sources in the core.

**Comment by yurabakhtin** [comment]
> Just discussed: Let's go with completely hide unknown invite sources in the core.

@luke- Commit https://github.com/humhub/humhub/pull/7229/commits/7bdd5f3d9e4fea641e309c3680905a9c33bf42f1.

**Comment by luke-** [comment]
@yurabakhtin Thank you. Can you please change the PR base to `develop`.

**Comment by yurabakhtin** [comment]
@luke- Done.
